"use client"

import { useState } from "react"
import Image from "next/image"
import { cn } from "@/lib/utils"
import { Lightbox } from "@/components/Lightbox"

/* ------------------------------------------------------------------ */
/*  Theme catalog — one entry per coco preset. `accent` is the         */
/*  theme's signature hue, used to tint the hover glow and the         */
/*  featured-preview atmosphere. Screenshots live in                   */
/*  /public/screenshots/theme-<slug>.png and are regenerated by the    */
/*  VHS pipeline (each paired with its matching terminal palette).     */
/* ------------------------------------------------------------------ */

export interface ThemeTile {
  name: string
  slug: string
  accent: string
}

const THEMES: ThemeTile[] = [
  { name: "Catppuccin", slug: "catppuccin", accent: "#89b4fa" },
  { name: "Gruvbox", slug: "gruvbox", accent: "#fabd2f" },
  { name: "Dracula", slug: "dracula", accent: "#bd93f9" },
  { name: "Nord", slug: "nord", accent: "#88c0d0" },
  { name: "Tokyo Night", slug: "tokyo-night", accent: "#7aa2f7" },
  { name: "One Dark", slug: "one-dark", accent: "#61afef" },
  { name: "Rosé Pine", slug: "rose-pine", accent: "#c4a7e7" },
  { name: "Kanagawa", slug: "kanagawa", accent: "#7e9cd8" },
  { name: "Everforest", slug: "everforest", accent: "#a7c080" },
  { name: "Monokai", slug: "monokai", accent: "#a6e22e" },
  { name: "Synthwave", slug: "synthwave", accent: "#f97e72" },
  { name: "Ayu Dark", slug: "ayu-dark", accent: "#e6b450" },
  { name: "Palenight", slug: "palenight", accent: "#82aaff" },
  { name: "GitHub Dark", slug: "github-dark", accent: "#58a6ff" },
  { name: "Horizon", slug: "horizon", accent: "#e95678" },
  { name: "Nightfox", slug: "nightfox", accent: "#719cd6" },
  { name: "Carbonfox", slug: "carbonfox", accent: "#78a9ff" },
  { name: "Tokyonight Storm", slug: "tokyonight-storm", accent: "#7aa2f7" },
  { name: "Iceberg", slug: "iceberg", accent: "#84a0c6" },
  { name: "Material Ocean", slug: "material-ocean", accent: "#82aaff" },
  { name: "Moonlight", slug: "moonlight", accent: "#c099ff" },
  { name: "Poimandres", slug: "poimandres", accent: "#5de4c7" },
  { name: "Vitesse Dark", slug: "vitesse-dark", accent: "#4d9375" },
  { name: "Vesper", slug: "vesper", accent: "#ffc799" },
  { name: "Flexoki", slug: "flexoki", accent: "#4385be" },
  { name: "Mellow", slug: "mellow", accent: "#aca1cf" },
  { name: "Solarized Dark", slug: "solarized-dark", accent: "#268bd2" },
  { name: "Solarized Light", slug: "solarized-light", accent: "#b58900" },
  { name: "Catppuccin Latte", slug: "catppuccin-latte", accent: "#1e66f5" },
  { name: "GitHub Light", slug: "github-light", accent: "#0969da" },
  { name: "Monochrome", slug: "monochrome", accent: "#9ca3af" },
]

/** Split the catalog into N roughly-even marquee rows. */
function intoRows<T>(items: T[], rows: number): T[][] {
  const out: T[][] = Array.from({ length: rows }, () => [])
  items.forEach((item, i) => out[i % rows]!.push(item))
  return out
}

function Tile({
  theme,
  onHover,
  active,
}: {
  theme: ThemeTile
  onHover: (t: ThemeTile | null) => void
  active: boolean
}) {
  const src = `/screenshots/theme-${theme.slug}.png`
  return (
    <Lightbox src={src} alt={`coco ui — ${theme.name} theme`}>
      <figure
        onMouseEnter={() => onHover(theme)}
        onMouseLeave={() => onHover(null)}
        className={cn(
          "group/tile relative w-[260px] shrink-0 overflow-hidden rounded-md border bg-bg-elevated transition-all duration-300 sm:w-[300px]",
          "border-border/60 hover:z-10 hover:scale-[1.04]"
        )}
        style={{
          boxShadow: active ? `0 0 0 1px ${theme.accent}, 0 12px 40px -12px ${theme.accent}80` : undefined,
          borderColor: active ? theme.accent : undefined,
        }}
      >
        <Image
          src={src}
          alt={`coco ui — ${theme.name} theme`}
          width={1260}
          height={800}
          className="h-auto w-full object-cover object-top"
          sizes="300px"
        />
        {/* Name badge — slides up on hover */}
        <figcaption
          className="pointer-events-none absolute inset-x-0 bottom-0 translate-y-full bg-gradient-to-t from-black/85 to-transparent px-3 pb-2 pt-6 font-mono text-xs font-medium text-white transition-transform duration-300 group-hover/tile:translate-y-0"
        >
          <span
            className="mr-1.5 inline-block h-2 w-2 rounded-full align-middle"
            style={{ backgroundColor: theme.accent }}
          />
          {theme.name}
        </figcaption>
      </figure>
    </Lightbox>
  )
}

interface MarqueeRowProps {
  themes: ThemeTile[]
  duration: number
  reverse?: boolean
  onHover: (t: ThemeTile | null) => void
  activeSlug: string | null
}

function MarqueeRow({ themes, duration, reverse, onHover, activeSlug }: MarqueeRowProps) {
  // Duplicate the row so the translateX loop is seamless.
  const doubled = [...themes, ...themes]
  return (
    <div className="group/row relative flex overflow-hidden">
      <div
        className="flex shrink-0 gap-4 pr-4 group-hover/row:[animation-play-state:paused]"
        style={{
          animation: `theme-marquee ${duration}s linear infinite`,
          animationDirection: reverse ? "reverse" : "normal",
        }}
      >
        {doubled.map((theme, i) => (
          <Tile
            key={`${theme.slug}-${i}`}
            theme={theme}
            onHover={onHover}
            active={activeSlug === theme.slug}
          />
        ))}
      </div>
    </div>
  )
}

/**
 * Kinetic wall of every coco theme. Three marquee rows scroll in
 * alternating directions and pause on hover; hovering a tile lifts it,
 * rings it in the theme's accent, and bleeds that hue into the section.
 * Click any tile for a full-size lightbox. Replaces the old one-at-a-time
 * arrow carousel — 30 palettes shown at once instead of one every click.
 */
export function ThemeWall({ className }: { className?: string }) {
  const [active, setActive] = useState<ThemeTile | null>(null)
  const rows = intoRows(THEMES, 3)

  return (
    <div className={cn("relative", className)}>
      {/* Accent atmosphere — tints toward the hovered theme */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 -z-10 opacity-0 blur-3xl transition-all duration-700"
        style={{
          opacity: active ? 0.18 : 0,
          background: active
            ? `radial-gradient(ellipse 60% 50% at 50% 50%, ${active.accent}, transparent 70%)`
            : undefined,
        }}
      />

      {/* Edge fades so tiles dissolve in/out rather than hard-clipping */}
      <div className="pointer-events-none absolute inset-y-0 left-0 z-20 w-16 bg-gradient-to-r from-background to-transparent sm:w-28" />
      <div className="pointer-events-none absolute inset-y-0 right-0 z-20 w-16 bg-gradient-to-l from-background to-transparent sm:w-28" />

      <div className="flex flex-col gap-4">
        <MarqueeRow themes={rows[0]!} duration={64} onHover={setActive} activeSlug={active?.slug ?? null} />
        <MarqueeRow themes={rows[1]!} duration={78} reverse onHover={setActive} activeSlug={active?.slug ?? null} />
        <MarqueeRow themes={rows[2]!} duration={70} onHover={setActive} activeSlug={active?.slug ?? null} />
      </div>

      {/* Live caption — name of whatever you're pointing at */}
      <div className="mt-6 flex items-center justify-center gap-2 font-mono text-sm">
        <span
          className="inline-block h-2.5 w-2.5 rounded-full transition-colors duration-300"
          style={{ backgroundColor: active?.accent ?? "hsl(var(--muted-foreground))" }}
        />
        <span className="text-muted-foreground">
          {active ? (
            <>
              <span className="font-semibold text-foreground">{active.name}</span>
              <span className="text-muted-foreground/60"> · click to enlarge</span>
            </>
          ) : (
            <>
              <span className="font-semibold text-foreground">{THEMES.length} built-in themes</span>
              <span className="text-muted-foreground/60"> · hover to pause, click to enlarge</span>
            </>
          )}
        </span>
      </div>

      <style jsx>{`
        @keyframes theme-marquee {
          from {
            transform: translateX(0);
          }
          to {
            transform: translateX(-50%);
          }
        }
      `}</style>
    </div>
  )
}
