export const siteConfig = {
  name: "Coco",
  url: "https://coco.griffen.codes",
  ogImage: "https://coco.griffen.codes/og-image.png",
  description:
    "A suite of AI-powered Git tools — smart commits, automated changelogs, code reviews, commit splitting, and recaps — plus a keyboard-driven terminal workstation that brings them all together. Supports OpenAI, Anthropic, and Ollama for local/private operation.",
  keywords: [
    "git",
    "cli tool",
    "AI git commits",
    "automated changelogs",
    "code review",
    "commit splitting",
    "terminal git workstation",
    "developer tools",
    "AI assistant",
    "conventional commits",
    "git automation",
    "terminal tools",
    "git tui",
    "coco ui",
    "commit messages",
    "changelog generator",
    "ollama",
    "openai",
    "anthropic",
  ],
  links: {
    docs: "/docs",
    workstation: "/workstation",
    changelog: "/changelog",
    github: "https://github.com/gfargo/coco",
    githubProfile: "https://github.com/gfargo",
    discord: "https://discord.gg/KGu9nE9Ejx",
    npm: "https://www.npmjs.com/package/git-coco",
    discussions: "https://github.com/gfargo/coco/discussions",
    issues: "https://github.com/gfargo/coco/issues/new",
    wiki: "https://github.com/gfargo/coco/wiki",
    ollamaWiki: "https://github.com/gfargo/coco/wiki/Using-Ollama",
    commitPrompt:
      "https://github.com/gfargo/coco/blob/main/src/lib/langchain/prompts/commitDefault.ts#L3-L15",
  },
  author: {
    name: "Griffen Fargo",
    url: "https://github.com/gfargo",
    twitter: "@gfargo",
  },
}
