/**
 * Canonical catalog of coco's built-in color themes — the single source
 * of truth shared by the marketing theme wall and the /docs/themes page.
 *
 * `accent` is the theme's signature hue (used for glow / swatches).
 * `mode` drives the dark / light grouping. Screenshots live at
 * /public/screenshots/theme-<slug>.png, regenerated by the VHS pipeline.
 */
export interface ThemeMeta {
  name: string
  slug: string
  accent: string
  mode: "dark" | "light"
  blurb: string
}

export const THEMES: ThemeMeta[] = [
  { name: "Catppuccin", slug: "catppuccin", accent: "#89b4fa", mode: "dark", blurb: "Soft pastels on deep navy — the community favorite, easy on the eyes." },
  { name: "Gruvbox", slug: "gruvbox", accent: "#fabd2f", mode: "dark", blurb: "Warm retro browns and ambers — cozy and high-contrast." },
  { name: "Dracula", slug: "dracula", accent: "#bd93f9", mode: "dark", blurb: "Purple-accented dark — bold, vibrant, unmistakable." },
  { name: "Nord", slug: "nord", accent: "#88c0d0", mode: "dark", blurb: "Arctic blue-grays — calm, cool, and focused." },
  { name: "Tokyo Night", slug: "tokyo-night", accent: "#7aa2f7", mode: "dark", blurb: "Neon city lights on midnight blue — modern and sharp." },
  { name: "One Dark", slug: "one-dark", accent: "#61afef", mode: "dark", blurb: "Atom's classic palette — familiar and balanced." },
  { name: "Rosé Pine", slug: "rose-pine", accent: "#c4a7e7", mode: "dark", blurb: "Muted mauve and rose on plum — gentle and elegant." },
  { name: "Kanagawa", slug: "kanagawa", accent: "#7e9cd8", mode: "dark", blurb: "Inspired by Hokusai's wave — serene, earthy, distinctive." },
  { name: "Everforest", slug: "everforest", accent: "#a7c080", mode: "dark", blurb: "Soft forest greens — natural and restful." },
  { name: "Monokai", slug: "monokai", accent: "#a6e22e", mode: "dark", blurb: "The Sublime classic — vivid syntax on warm charcoal." },
  { name: "Synthwave", slug: "synthwave", accent: "#f97e72", mode: "dark", blurb: "Retro neon on indigo — cyberpunk vibes." },
  { name: "Ayu Dark", slug: "ayu-dark", accent: "#e6b450", mode: "dark", blurb: "Golden accents on near-black — clean and minimal." },
  { name: "Palenight", slug: "palenight", accent: "#82aaff", mode: "dark", blurb: "Material-inspired soft indigo — refined and mellow." },
  { name: "GitHub Dark", slug: "github-dark", accent: "#58a6ff", mode: "dark", blurb: "GitHub's own dark palette — familiar and professional." },
  { name: "Horizon", slug: "horizon", accent: "#e95678", mode: "dark", blurb: "Warm coral and rose on dusk — inviting sunset tones." },
  { name: "Nightfox", slug: "nightfox", accent: "#719cd6", mode: "dark", blurb: "Deep blues with cool accents — focused and quiet." },
  { name: "Carbonfox", slug: "carbonfox", accent: "#78a9ff", mode: "dark", blurb: "IBM Carbon-inspired near-black — sharp, professional edge." },
  { name: "Tokyonight Storm", slug: "tokyonight-storm", accent: "#7aa2f7", mode: "dark", blurb: "The stormier Tokyo Night variant — deeper, softer contrast." },
  { name: "Iceberg", slug: "iceberg", accent: "#84a0c6", mode: "dark", blurb: "Cool blue-gray minimalism — crisp and understated." },
  { name: "Material Ocean", slug: "material-ocean", accent: "#82aaff", mode: "dark", blurb: "Deep ocean blues — immersive Material palette." },
  { name: "Moonlight", slug: "moonlight", accent: "#c099ff", mode: "dark", blurb: "Soft moonlit blues and violets — dreamy after-dark." },
  { name: "Poimandres", slug: "poimandres", accent: "#5de4c7", mode: "dark", blurb: "Teal and lavender on slate — modern dev aesthetic." },
  { name: "Vitesse Dark", slug: "vitesse-dark", accent: "#4d9375", mode: "dark", blurb: "Antfu's muted greens — understated and easy." },
  { name: "Vesper", slug: "vesper", accent: "#ffc799", mode: "dark", blurb: "Warm amber and teal on charcoal — a cozy evening." },
  { name: "Flexoki", slug: "flexoki", accent: "#4385be", mode: "dark", blurb: "Ink-on-paper inspired — organic, warm-leaning palette." },
  { name: "Mellow", slug: "mellow", accent: "#aca1cf", mode: "dark", blurb: "Soft, low-saturation pastels — gentle on the eyes." },
  { name: "Solarized Dark", slug: "solarized-dark", accent: "#268bd2", mode: "dark", blurb: "The precision-contrast classic — timeless teal base." },
  { name: "Solarized Light", slug: "solarized-light", accent: "#b58900", mode: "light", blurb: "Solarized on warm cream — easy daylight reading." },
  { name: "Catppuccin Latte", slug: "catppuccin-latte", accent: "#1e66f5", mode: "light", blurb: "The light Catppuccin flavor — soft and airy." },
  { name: "GitHub Light", slug: "github-light", accent: "#0969da", mode: "light", blurb: "GitHub's light palette — clean, neutral, familiar." },
  { name: "Monochrome", slug: "monochrome", accent: "#9ca3af", mode: "dark", blurb: "Pure grayscale — distraction-free, and the NO_COLOR baseline." },
  { name: "Night Owl", slug: "night-owl", accent: "#82aaff", mode: "dark", blurb: "Deep teal-navy with soft blues — tuned for late-night coding." },
  { name: "Cobalt2", slug: "cobalt2", accent: "#ffc600", mode: "dark", blurb: "Vivid cobalt blue with a signature yellow accent — bold and bright." },
  { name: "Oceanic Next", slug: "oceanic-next", accent: "#6699cc", mode: "dark", blurb: "Muted ocean blues and greens — calm and balanced." },
  { name: "Catppuccin Macchiato", slug: "catppuccin-macchiato", accent: "#8aadf4", mode: "dark", blurb: "The warmer mid-dark Catppuccin flavor — soft pastels, deeper base." },
  { name: "Gruvbox Light", slug: "gruvbox-light", accent: "#076678", mode: "light", blurb: "Gruvbox on warm cream — retro warmth for daylight." },
  { name: "Tokyo Night Day", slug: "tokyo-night-day", accent: "#2e7de9", mode: "light", blurb: "The daylight Tokyo Night — crisp blues on a soft gray canvas." },
]

export const THEME_COUNT = THEMES.length
