import { Section } from "@/components/Section";
import { GitCommitHorizontalIcon, ScrollTextIcon } from "lucide-react";

import cocoCommitImage from "@/assets/coco-basic-commit.png";
import cocoCommitHeaderUpdateGif from "@/assets/gifs/commit-basic-header-update.gif";
import cocoCommitBigGif from "@/assets/gifs/commit-big.gif";
import cocoCommitRandom from "@/assets/gifs/commit-random-assortment.gif";
import cocoCommitWithStatus from "@/assets/gifs/commit-with-status.gif";

import cocoChangelogImage from "@/assets/coco-changelog.png";
import cocoChangelogRangeGif from "@/assets/gifs/changelog-range.gif";

import Image from "next/image";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export const FeaturesSection = () => {
  const imageClass = " border-8 border-[#1e1f28] space-y-4 max-w-full";
  const tabContentClass =
    "mx-auto order-2 md:order-1 overflow-hidden rounded-xl object-cover object-center justify-center bg-[#1e1f28]";

  return (
    <Section id="features" className="bg-white text-secondary">
      <div className="container px-4 md:px-6">
        <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-center mb-12 lg:mb-16 text-primary ">
          features
        </h2>
        <div className="grid gap-12 md:gap-18 lg:gap-20 md:grid-cols-1 lg:grid-cols-1">
          <Tabs
            defaultValue="basic"
            className="flex flex-col space-y-4 md:flex-row md:space-x-4 lg:flex-row lg:space-x-8 md:items-center"
          >
            <TabsContent value="basic" className={tabContentClass}>
              <Image
                src={cocoCommitWithStatus}
                alt="example of commit message generated by coco"
                className={imageClass}
              />
            </TabsContent>
            <TabsContent value="react" className={tabContentClass}>
              <Image
                src={cocoCommitHeaderUpdateGif}
                alt="example of commit message generated by coco"
                className={imageClass}
              />
            </TabsContent>
            <TabsContent value="big" className={tabContentClass}>
              <Image
                src={cocoCommitBigGif}
                alt="example of commit message generated by coco"
                className={imageClass}
              />
            </TabsContent>
            <TabsContent value="random" className={tabContentClass}>
              <Image
                src={cocoCommitRandom}
                alt="example of commit message generated by coco"
                className={imageClass}
              />
            </TabsContent>

            <div className="order-1 md:order-2 space-y-4 max-w-lg">
              <h2 className="text-2xl font-bold">
                <GitCommitHorizontalIcon className="inline" /> Commits
              </h2>
              <p className="text-base text-zinc-500 dark:text-zinc-400">
                generate commit messages with ease.
              </p>
              <TabsList>
                <TabsTrigger value="basic">Basic</TabsTrigger>
                <TabsTrigger value="react">React Component</TabsTrigger>
                <TabsTrigger value="big" className="hidden md:inline-flex">
                  Big Commit
                </TabsTrigger>
                <TabsTrigger value="random" className="hidden md:inline-flex">
                  Random
                </TabsTrigger>
              </TabsList>
            </div>
          </Tabs>

          <Separator />

          <Tabs
            defaultValue="range"
            className="flex flex-col space-y-4 md:flex-row md:space-x-4 lg:flex-row lg:space-x-8 items-center"
          >
            <div className="order-1 md:order-1 lg:order-1 space-y-4 max-w-lg">
              <h2 className="text-2xl font-bold">
                <ScrollTextIcon className="inline" /> Changelogs
              </h2>
              <p className="text-base text-zinc-500 dark:text-zinc-400">
                generate changelogs from your current branch or from a range of
                commits.
              </p>

              <TabsList>
                <TabsTrigger value="current-branch" disabled>
                  Current Branch (coming soon)
                </TabsTrigger>
                <TabsTrigger value="range">Range</TabsTrigger>
              </TabsList>
            </div>
            <TabsContent
              value="current-branch"
              className="mx-auto order-2 md:order-1 lg:order-1 overflow-hidden rounded-xl object-cover object-center sm:w-full border-8 border-[#1e1f28]"
            >
              <Image
                src={cocoChangelogImage}
                alt="example of changelog generated by coco"
              />
            </TabsContent>
            <TabsContent value="range" className={tabContentClass}>
              <Image
                src={cocoChangelogRangeGif}
                alt="changelog generated by coco from a commit range"
              />
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </Section>
  );
};
